export const menuItems =
[
    // {icon: 'pi pi-home' , label: 'DASHBOARD' , route: '/dashboard'},
    // {icon: 'pi pi-users' , label: 'CLIENTS' , route: '/clients'},
    // {icon: 'pi pi-truck' , label: 'ORDERS' , route: '/orders'},
    // {icon: 'pi pi-users' , label: 'PROVIDERS' , route: '/providers'},
    {icon: 'pi pi-clock' , label: 'WORKING HOURS' , route: '/working_hours'},
    {icon: 'pi pi-globe' , label: 'COUNTRIES' , route: '/country'},
    {icon: 'pi pi-building' , label: 'CITIES' , route: '/city'},
    {icon: 'pi pi-times' , label: 'CANCEL REASON' , route: '/cancel-reason'},
    {icon: 'pi pi-book' , label: 'COMPLAINT' , route: '/complaint'},
    {icon: 'pi pi-folder' , label: 'CONTRACT TYPE' , route: '/contract-type'},
    {icon: 'pi pi-qrcode' , label: 'COPONE' , route: '/copone'},


]


export const products=[
    {
      id: '1',
      code: 'f230fh0g3',
      name: 'Bamboo Watch',
      description: 'Product Description',
      imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
      asd:{
           name:'aaaa',
           image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
      },
      price: 65,
      category: 'Accessories',
      quantity: 24,
      inventoryStatus: 'INSTOCK',
      rating: 5,
      status:'complete'
  },
  {
    id: '2',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'inProgress',
    asd:{
      name:'mmm',
      image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  },
  {
    id: '3',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'cancel',
    asd:{
      name:'ccc',
      image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  },
  {
    id: '4',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'cancel',
    asd:{
      name:'ccc',
      image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  },
  {
    id: '5',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'cancel',
    asd:{
      name:'ccc',
      image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  },
  {
    id: '6',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    asd:{
         name:'aaaa',
         image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
    },
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'complete'
},
{
  id: '7',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'inProgress',
  asd:{
    name:'mmm',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '8',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '9',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    asd:{
         name:'aaaa',
         image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
    },
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'complete'
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'inProgress',
  asd:{
    name:'mmm',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  asd:{
       name:'aaaa',
       image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'complete'
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'inProgress',
asd:{
  name:'mmm',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    asd:{
         name:'aaaa',
         image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
    },
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'complete'
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'inProgress',
  asd:{
    name:'mmm',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  asd:{
       name:'aaaa',
       image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'complete'
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'inProgress',
asd:{
  name:'mmm',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    asd:{
         name:'aaaa',
         image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
    },
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'complete'
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'inProgress',
  asd:{
    name:'mmm',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  asd:{
       name:'aaaa',
       image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'complete'
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'inProgress',
asd:{
  name:'mmm',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
    asd:{
         name:'aaaa',
         image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
    },
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
    status:'complete'
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'inProgress',
  asd:{
    name:'mmm',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'cancel',
  asd:{
    name:'ccc',
    image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
  id: '1000',
  code: 'f230fh0g3',
  name: 'Bamboo Watch',
  description: 'Product Description',
  imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
  asd:{
       name:'aaaa',
       image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
  },
  price: 65,
  category: 'Accessories',
  quantity: 24,
  inventoryStatus: 'INSTOCK',
  rating: 5,
  status:'complete'
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'inProgress',
asd:{
  name:'mmm',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},
{
id: '1000',
code: 'f230fh0g3',
name: 'Bamboo Watch',
description: 'Product Description',
imaged: 'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg',
price: 65,
category: 'Accessories',
quantity: 24,
inventoryStatus: 'INSTOCK',
rating: 5,
status:'cancel',
asd:{
  name:'ccc',
  image:'https://primefaces.org/cdn/primeng/images/demo/product/bamboo-watch.jpg'
},
},


  ]
