/**
 * Centralized API endpoints mapping.
 * All endpoints are relative to the base URL (e.g., https://backend.matlop.com/api/).
 */
export const API = {
  AUTH: {
    ADMIN_LOGIN: 'auth/admin-login',
    LOGIN: 'auth/login',
    VERIFY_OTP: 'auth/verify-otp',
    FORGOT_PASSWORD: 'auth/forgot-password',
    RESET_PASSWORD: 'auth/reset-password',
    VERIFY_RESET_CODE: 'auth/verify-reset-code',
    CHANGE_PASSWORD: 'auth/change-password',
    MENU: 'auth/menu',
    LOGOUT: 'auth/logout',
    VALIDATE_TOKEN: 'auth/validate-token',
  },
  ADMINS: {
    BASE: 'admins',
    SEARCH: 'admins/search',
    BY_ID: (id: string | number) => `admins/${id}`,
  },
  CLIENTS: {
    BASE: 'clients',
    SEARCH: 'clients/search',
    BY_ID: (id: string | number) => `clients/${id}`,
    BY_TYPE: (typeId: string | number) => `clients/by-type/${typeId}`,
    BY_TYPE_AND_COUNTRY: 'clients/by-type-and-country',
    ACTIVATE: (userId: string | number) => `clients/${userId}/activate`,
  },
  ORDERS: {
    BASE: 'orders',
    SEARCH: 'orders/search',
    SEARCH_DASHBOARD: 'orders/search/dashboard',
    BY_ID: (id: string | number) => `orders/${id}`,
    BY_CLIENT: (clientId: string | number) => `orders/by-client/${clientId}`,
    BY_TECHNICAL: (techId: string | number) => `orders/by-technical/${techId}`,
    CANCEL: (orderId: string | number) => `orders/${orderId}/cancel`,
    STATUS: (orderId: string | number) => `orders/${orderId}/status`,
    MARK_PAID: (orderId: string | number) => `orders/${orderId}/mark-paid`,
    ASSIGN_TECHNICAL: (orderId: string | number) => `orders/${orderId}/assign-technical`,
    DELETE_ASSIGN_TECHNICAL: (orderId: string | number, id: string | number) => `orders/${orderId}/assign-technical/${id}`,
    EXPORT_EXCEL: 'orders/export-excel',
  },
  SPECIAL_ORDERS: {
    BASE: 'special-orders',
    SEARCH: 'special-orders/search',
    BY_ID: (id: string | number) => `special-orders/${id}`,
    BY_CLIENT: (clientId: string | number) => `special-orders/by-client/${clientId}`,
    NEW_BY_COUNTRY: (countryId: string | number) => `special-orders/by-country/${countryId}/new`,
    ASSIGN_TECHNICAL: (orderId: string | number) => `special-orders/${orderId}/assign-technical`,
    DELETE_ASSIGN_TECHNICAL: (orderId: string | number, id: string | number) => `special-orders/${orderId}/assign-technical/${id}`,
  },
  SPECIAL_ORDER_OFFERS: {
    BASE: 'special-order-offers',
    BY_SPECIAL_ORDER: (id: string | number) => `special-order-offers/by-special-order/${id}`,
    SUBMIT: 'special-order-offers/submit',
  },
  ORDER_ADDITIONAL_ITEMS: {
    BASE: 'order-additional-items',
    BY_ORDER: (orderId: string | number) => `order-additional-items/by-order/${orderId}`,
    BY_ID: (id: string | number) => `order-additional-items/${id}`,
  },
  ORDER_DEFAULT_IMAGES: {
    BASE: 'order-default-images',
    SPECIAL_ORDER: 'order-default-images/special-order',
    EMERGENCY: 'order-default-images/emergency',
  },
  SERVICES: {
    BASE: 'services',
    SEARCH: 'services/search',
    BY_ID: (id: string | number) => `services/${id}`,
  },
  CONTRACT_TYPES: {
    BASE: 'contract-types',
    SEARCH: 'contract-types/search',
    BY_ID: (id: string | number) => `contract-types/${id}`,
    BY_SERVICE: (serviceId: string | number) => `contract-types/by-service/${serviceId}`,
  },
  PACKAGES: {
    BASE: 'packages',
    SEARCH: 'packages/search',
    BY_ID: (id: string | number) => `packages/${id}`,
    BY_CONTRACT: (contractId: string | number) => `packages/by-contract/${contractId}`,
    BY_CITY: (cityId: string | number) => `packages/by-city/${cityId}`,
    WORK_TIMES: (packageId: string | number) => `packages/${packageId}/work-times`,
    MOST_REQUESTED: 'packages/most-requested',
  },
  EQUIPMENT: {
    BASE: 'equipment',
    SEARCH: 'equipment/search',
    BY_ID: (id: string | number) => `equipment/${id}`,
    BY_PACKAGE: (packageId: string | number) => `equipment/by-package/${packageId}`,
  },
  TECHNICALS: {
    BASE: 'technicals',
    ACTIVE: 'technicals/active',
    SEARCH: 'technicals/search',
    BY_ID: (id: string | number) => `technicals/${id}`,
  },
  TECHNICAL_SPECIALISTS: {
    BASE: 'technical-specialists',
    SEARCH: 'technical-specialists/search',
    BY_ID: (id: string | number) => `technical-specialists/${id}`,
  },
  COUNTRIES: {
    BASE: 'countries',
    SEARCH: 'countries/search',
    BY_ID: (id: string | number) => `countries/${id}`,
  },
  CITIES: {
    BASE: 'cities',
    SEARCH: 'cities/search',
    BY_ID: (id: string | number) => `cities/${id}`,
    BY_COUNTRY: (countryId: string | number) => `cities/by-country/${countryId}`,
  },
  DISTRICTS: {
    BASE: 'districts',
    SEARCH: 'districts/search',
    BY_ID: (id: string | number) => `districts/${id}`,
    BY_CITY: (cityId: string | number) => `districts/by-city/${cityId}`,
  },
  LOCATIONS: {
    BASE: 'locations',
    BY_ID: (id: string | number) => `locations/${id}`,
    BY_USER: (userId: string | number) => `locations/by-user/${userId}`,
  },
  FAQS: {
    BASE: 'faqs',
    SEARCH: 'faqs/search',
    BY_ID: (id: string | number) => `faqs/${id}`,
    BY_COUNTRY: (countryId: string | number) => `faqs/by-country/${countryId}`,
  },
  BLOGS: {
    BASE: 'blogs',
    SEARCH: 'blogs/search',
    BY_ID: (id: string | number) => `blogs/${id}`,
    LATEST_DISPLAY_ORDER: (countryId: string | number) => `blogs/latest-display-order/${countryId}`,
  },
  SLIDERS: {
    BASE: 'sliders',
    BY_ID: (id: string | number) => `sliders/${id}`,
    BY_COUNTRY: (countryId: string | number) => `sliders/by-country/${countryId}`,
  },
  TERMS_AND_CONDITIONS: {
    BASE: 'terms-and-conditions',
    SEARCH: 'terms-and-conditions/search',
    BY_ID: (id: string | number) => `terms-and-conditions/${id}`,
    BY_USER_TYPE: 'terms-and-conditions/by-user-type',
    BY_COUNTRY: (countryId: string | number) => `terms-and-conditions/by-country/${countryId}`,
  },
  PRIVACY_POLICIES: {
    BASE: 'privacy-policies',
    SEARCH: 'privacy-policies/search',
    BY_ID: (id: string | number) => `privacy-policies/${id}`,
    BY_USER_TYPE: 'privacy-policies/by-user-type',
    BY_COUNTRY: (countryId: string | number) => `privacy-policies/by-country/${countryId}`,
  },
  ABOUT_US: {
    BASE: 'about-us',
    SEARCH: 'about-us/search',
    BY_ID: (id: string | number) => `about-us/${id}`,
    BY_COUNTRY: (countryId: string | number) => `about-us/by-country/${countryId}`,
  },
  CONTACT_US: {
    BASE: 'contact-us',
    SEARCH: 'contact-us/search',
    BY_ID: (id: string | number) => `contact-us/${id}`,
  },
  OUR_CLIENTS: {
    BASE: 'our-clients',
    SEARCH: 'our-clients/search',
    BY_ID: (id: string | number) => `our-clients/${id}`,
    BY_COUNTRY: (countryId: string | number) => `our-clients/by-country/${countryId}`,
  },
  COMPLAINTS: {
    BASE: 'complaints',
    SEARCH: 'complaints/search',
    BY_ID: (id: string | number) => `complaints/${id}`,
  },
  CANCEL_REASONS: {
    BASE: 'cancel-reasons',
    SEARCH: 'cancel-reasons/search',
    BY_ID: (id: string | number) => `cancel-reasons/${id}`,
    BY_COUNTRY: (countryId: string | number) => `cancel-reasons/by-country/${countryId}`,
  },
  COUPONS: {
    BASE: 'coupons',
    SEARCH: 'coupons/search',
    BY_ID: (id: string | number) => `coupons/${id}`,
    VERIFY: (code: string, userId: string | number) => `coupons/verify/${code}/${userId}`,
  },
  PAYMENT_WAYS: {
    BASE: 'payment-ways',
    SEARCH: 'payment-ways/search',
    BY_ID: (id: string | number) => `payment-ways/${id}`,
  },
  PAYMENT_TRANSACTIONS: {
    BASE: 'payment-transactions',
    BY_ORDER: (orderId: string | number) => `payment-transactions/by-order/${orderId}`,
    CALLBACK: 'payment-transactions/callback',
    THAWANI: 'payment-transactions/thawani',
    THAWANI_CALLBACK: 'payment-transactions/thawani-callback',
  },
  WALLETS: {
    TRANSACTIONS: 'wallets/transactions',
    BALANCE: (clientId: string | number) => `wallets/${clientId}/balance`,
    CLIENT_TRANSACTIONS: (clientId: string | number) => `wallets/${clientId}/transactions`,
    CALCULATE: 'wallets/calculate',
  },
  WALLET_WITHDRAWALS: {
    SEARCH: 'wallet-withdrawals/search',
    APPROVE: 'wallet-withdrawals/approve',
  },
  WORKING_TIMES: {
    BASE: 'working-times',
    SEARCH: 'working-times/search',
    BY_ID: (id: string | number) => `working-times/${id}`,
  },
  NOTIFICATIONS: {
    BASE: 'notifications',
    SEEN: (id: string | number) => `notifications/${id}/seen`,
  },
  SERVICE_REVIEWS: {
    BASE: 'service-reviews',
    SEARCH: 'service-reviews/search',
    BY_ID: (id: string | number) => `service-reviews/${id}`,
    BY_USER: 'service-reviews/by-user',
    BY_USER_DASHBOARD: 'service-reviews/by-user-dashboard',
    BY_SERVICE: (serviceId: string | number) => `service-reviews/by-service/${serviceId}`,
  },
  TECHNICAL_REVIEWS: {
    BASE: 'technical-reviews',
    SEARCH: 'technical-reviews/search',
    CLIENT_REVIEW: 'technical-reviews/client-review',
    TECHNICAL_REVIEW: 'technical-reviews/technical-review',
    DELETE_TECHNICAL: (clientId: string | number, orderId: string | number) => `technical-reviews/technical/${clientId}/${orderId}`,
    DELETE_CLIENT: (technicalId: string | number, orderId: string | number) => `technical-reviews/client/${technicalId}/${orderId}`,
  },
  ROLES: {
    BASE: 'roles',
    BY_ID: (id: string | number) => `roles/${id}`,
    USER_PERMISSIONS: (userId: string | number) => `roles/user-permissions/${userId}`,
  },
  SETTINGS: {
    BY_COUNTRY: (countryId: string | number) => `settings/${countryId}`,
    UPDATE: 'settings',
  },
  DASHBOARD: {
    BASE: 'dashboard',
    ORDER_STATISTICS: 'dashboard/order-statistics',
  },
  APP_VERSIONS: {
    BASE: 'app-versions',
  },
  SOCIAL_MEDIA: {
    BASE: 'social-media',
  },
} as const;
